name: Deploy to ECR

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t ${{ secrets.ECR_REPOSITORY }} .

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag Docker image
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ AKIA2GROVGICPXSCZY7S }}.dkr.ecr.${{ ap-northeast-1 }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ AKIA2GROVGICPXSCZY7S }}.dkr.ecr.${{ ap-northeast-1 }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

